### PR TITLE
Lazy load fonts

### PR DESCRIPTION
**Pull request by leoadberg**
Previously, Pixlet would render all fonts on initialization which would actually take a significant amount of time, mainly in `bdf.Parse()`. On any given Pixlet invocation it's unlikely all of the fonts would be used so we can save time by lazy loading them.

On my super underpowered Raspberry Pi it would previously take ~3.5s on average just to run `./pixlet` with no actions, and now it's down to ~0.35s, 10x faster! On my Mac it was already pretty fast but still got a ~3x speedup.

Other changes:

`FontDataRaw` -> `fontDataRaw` because I feel like it shouldn't be exported, but I'd be happy to revert that if needed.

Previously Pixlet would crash with an unhelpful message if an invalid font was selected because `Font[name]` would just return the empty struct:
```
Error: error running script: panic while running test.star: runtime error: invalid memory address or nil pointer dereference
```
I changed it to panic early in `GetFont(name)` with a more helpful error message:
```
Error: error running script: panic while running test.star: Unknown font 'badfont', the available fonts are: [tb-8 tom-thumb 10x20 5x8 6x13 CG-pixel-3x5-mono CG-pixel-4x5-mono Dina_r400-6]
```
(The behavior is still the same, just crashes earlier in a clearer way)

### CODE REVIEW

**Comment by rs7q5** [comment]
Heads up, the vertical messages app allows users to select the font they want (. It lists all available fonts and then switches based on user input. 

The list of fonts is grabbed using `render.fonts.items()`. This may not matter since only one font is chosen at a time. I don't think the app would be effected though? 

Although I guess since you're lazy loading does that mean if an app used all the fonts then it would just load all of them like it does now anyways?

**Comment by leoadberg** [comment]
> The list of fonts is grabbed using `render.fonts.items()`. This may not matter since only one font is chosen at a time. I don't think the app would be effected though?

`render.fonts` works the exact same way with this change so nothing should change, but thanks for the heads up! (It grabs the font names from `fontDataRaw` without needing to parse the fonts, which is the expensive part)

**Comment by rs7q5** [comment]
Yeah, I reread your comment and realized it shouldn't change it, but I just wanted to make sure I was understanding correctly.

**Comment by leoadberg** [comment]
Hey @betterengineering sorry for the ping but I just want to check, is there anything I should do to get this approved? Thanks!

**Pull request merged**
